### ISSUE TITLE
EOFError: End Of File (EOF). Exception style platform.

### ISSUE THREAD

**Issue by horseinthesky** [carlmontanari/scrapli#18]
**Describe the bug**
`EOFError: End Of File (EOF). Exception style platform.`
when trying to configure CSR1000v .

**To Reproduce**
```
from scrapli.driver.core import IOSXEDriver, JunosDriver

device_data = {
    'host': '10.10.30.6',
    'auth_username': 'admin',
    'auth_password': 'admin',
    'auth_strict_key': False,
    'transport': 'system'
}

commands = [
    'username horseinthesky privilege 15',
    'ip ssh pubkey-chain',
    'username horseinthesky',
    'key-string',
    'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCYY6EgT/vLzN3GRk2+7VZl3SgNofl066ZpIEdslS5kSHn7ziwtCB7RYfcgj+ASr95helTkyVY2w+kaJEzk0RRv+cZIYB4gChuSyL73aQNrLJtgiHQuQpqJcnPAbHk589SZpraxdphe92lvyguwpeJniT713t4IPjKcwRs9M9S66coUcVV+mpebw7al1Bp2/4QKaa3b62zcu4Z6V1ByH74pt',
    'Ihh5mSfu+hmMoKBh32P/+Ob6dCTjDi8VGfFm/taufSc6WYDvOdpg8GkBGgof6QnN0jxWdGUvVRO/1xgJOU8VrymEoJhE5ls3cMDaXeygemAiXbKGeIX/iBaGRWxV2GT horseinthesky@Kappa'
]

with IOSXEDriver(**device_data) as conn:
    output = conn.send_configs(commands)
```

**Expected behavior**
User `horseinthesky` must be configured and also an SSH RSA key for this user.

**Stack Trace**
```
Traceback (most recent call last):
  File "bla.py", line 27, in <module>
    output = conn.send_configs(commands)
  File "/usr/local/lib/python3.6/dist-packages/scrapli/driver/network_driver.py", line 518, in send_configs
    failed_when_contains=failed_when_contains,
  File "/usr/local/lib/python3.6/dist-packages/scrapli/driver/generic_driver.py", line 85, in send_command
    channel_input=command, strip_prompt=strip_prompt
  File "/usr/local/lib/python3.6/dist-packages/scrapli/channel/channel.py", line 269, in send_input
    channel_input=channel_input, strip_prompt=strip_prompt
  File "/usr/local/lib/python3.6/dist-packages/scrapli/decorators.py", line 78, in timeout_wrapper
    return future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/scrapli/channel/channel.py", line 297, in _send_input
    output = self._read_until_prompt()
  File "/usr/local/lib/python3.6/dist-packages/scrapli/channel/channel.py", line 214, in _read_until_prompt
    output += self._read_chunk()
  File "/usr/local/lib/python3.6/dist-packages/scrapli/channel/channel.py", line 146, in _read_chunk
    new_output = self.transport.read()
  File "/usr/local/lib/python3.6/dist-packages/scrapli/decorators.py", line 77, in timeout_wrapper
    raise TimeoutError(message)
TimeoutError: Timed out reading from transport

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bla.py", line 27, in <module>
    output = conn.send_configs(commands)
  File "/usr/local/lib/python3.6/dist-packages/scrapli/driver/driver.py", line 245, in __exit__
    self.close()
  File "/usr/local/lib/python3.6/dist-packages/scrapli/driver/driver.py", line 598, in close
    self.on_close(self)
  File "/usr/local/lib/python3.6/dist-packages/scrapli/driver/core/cisco_iosxe/driver.py", line 41, in iosxe_on_close
    conn.acquire_priv(desired_priv=conn.default_desired_privilege_level)
  File "/usr/local/lib/python3.6/dist-packages/scrapli/driver/network_driver.py", line 225, in acquire_priv
    current_priv = self._determine_current_priv(current_prompt=self.channel.get_prompt())
  File "/usr/local/lib/python3.6/dist-packages/scrapli/decorators.py", line 78, in timeout_wrapper
    return future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/scrapli/channel/channel.py", line 240, in get_prompt
    output += self._read_chunk()
  File "/usr/local/lib/python3.6/dist-packages/scrapli/channel/channel.py", line 146, in _read_chunk
    new_output = self.transport.read()
  File "/usr/local/lib/python3.6/dist-packages/scrapli/decorators.py", line 78, in timeout_wrapper
    return future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/scrapli/transport/systemssh.py", line 647, in read
    return self.session.read(read_bytes)
  File "/usr/local/lib/python3.6/dist-packages/scrapli/transport/ptyprocess.py", line 534, in read
    raise EOFError("End Of File (EOF). Exception style platform.")
EOFError: End Of File (EOF). Exception style platform.
```

**OS (please complete the following information):**
 - OS: Ubuntu 18.04.3 LTS
  be supported]
 - scrapli version 2020.4.30
 - version of any optional extras scrapli-ssh2==2020.4.30

**Additional context**
1) It is not dependent on what `transport` to use (tried `ssh2` and `system`)
2) It also brakes even with:
```
commands = [
    'username horseinthesky privilege 15',
    'ip ssh pubkey-chain',
]
```
3) Manual configuration work with no unexpected outputs:
```
CSR6(config)#ip ssh pubkey-chain
CSR6(conf-ssh-pubkey)#username horseinthesky
CSR6(conf-ssh-pubkey-user)#key-string
CSR6(conf-ssh-pubkey-data)#
*May  9 13:11:54.747: %DMI-5-SYNC_START: R0/0: syncfd: External change to running configuration detected. The running configuration will be synchronized to the NETCONF running data store.
CSR6(conf-ssh-pubkey-data)#$UcVV+mpebw7al1Bp2/4QKaa3b62zcu4Z6V1ByH74pt       
*May  9 13:11:59.934: %DMI-5-SYNC_COMPLETE: R0/0: syncfd: The running configuration has been synchronized to the NETCONF running data store.
CSR6(conf-ssh-pubkey-data)#$UcVV+mpebw7al1Bp2/4QKaa3b62zcu4Z6V1ByH74pt
CSR6(conf-ssh-pubkey-data)#
*May  9 13:12:04.290: %DMI-5-SYNC_START: R0/0: syncfd: External change to running configuration detected. The running configuration will be synchronized to the NETCONF running data store.
CSR6(conf-ssh-pubkey-data)#
*May  9 13:12:08.486: %DMI-5-SYNC_COMPLETE: R0/0: syncfd: The running configuration has been synchronized to the NETCONF running data store.
CSR6(conf-ssh-pubkey-data)#$eygemAiXbKGeIX/iBaGRWxV2GT horseinthesky@Kappa  
```

The result is correct:
```
ip ssh pubkey-chain
  username horseinthesky
   key-hash ssh-rsa D13E140448650E64A6778D40057326E8 horseinthesky@Kappa
```

**Comment by carlmontanari** [comment]
Hi @horseinthesky 

Thanks for submitting this (scrapli's first!) issue!

I was able to reproduce your example and it looks like it is a simple issue of the "configuration" privilege level prompt expecting the whole world "config" in the pattern instead of just "conf" as is shown when entering the ssh key config mode. 

The fix is to modify the configuration privilege level prompt pattern from:
```
"^[a-z0-9.\-@/:]{1,32}\(config[a-z0-9.\-@/:]{0,32}\)#$"
```

to:
```
"^[a-z0-9.\-@/:]{1,32}\(conf[a-z0-9.\-@/:]{0,32}\)#$"
```

Getting rid of the `ig` in `config` allows us to match on both the "normal" "config" pattern as well as the "conf" in the ssh key entry mode.

To prevent any future regression of this, I've added a test that ensures that the normal prompt (myrouter(config)#) as well as the ssh key mode prompt pattern are matched.

This fix is now in the develop branch, you can install the develop branch directly like so:

```
pip install -e git+https://github.com/carlmontanari/scrapli.git@develop#egg=scrapli
```

This will probably get merged into master and released to PyPi today or tomorrow as I was already planning on releasing an update.

One last, and important, note -- you will need to add an "exit" command to your list of commands in order for this to work with scrapli. To de-escalate back to privilege_exec, scrapli sends "end", however this does NOT work from the pubkey-chain prompt level, so without this additional "exit" command scrapli can never get back down to "privilege exec" mode.

Adding this extra "exit" command to your provided command list as follows works for me now (plus the bug fix of course!): 

```
commands = [
    'username horseinthesky privilege 15',
    'ip ssh pubkey-chain',
    'username horseinthesky',
    'key-string',
    'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCYY6EgT/vLzN3GRk2+7VZl3SgNofl066ZpIEdslS5kSHn7ziwtCB7RYfcgj+ASr95helTkyVY2w+kaJEzk0RRv+cZIYB4gChuSyL73aQNrLJtgiHQuQpqJcnPAbHk589SZpraxdphe92lvyguwpeJniT713t4IPjKcwRs9M9S66coUcVV+mpebw7al1Bp2/4QKaa3b62zcu4Z6V1ByH74pt',
    'Ihh5mSfu+hmMoKBh32P/+Ob6dCTjDi8VGfFm/taufSc6WYDvOdpg8GkBGgof6QnN0jxWdGUvVRO/1xgJOU8VrymEoJhE5ls3cMDaXeygemAiXbKGeIX/iBaGRWxV2GT horseinthesky@Kappa',
    'exit'
]
```

Thanks again for submitting this! As I was able to reproduce it and fix it I'm going to close this issue for now, but feel free to re-open if the fix does not work for you for any reason.

Carl

**Comment by horseinthesky** [comment]
This works like a charm. Thank you!

There is one more thing with deleting a user. I'm trying to do this with:
```
commands = [
    'no username horseinthesky',
    '\n'
    'ip ssh pubkey-chain',
    'no username horseinthesky',
    'exit'
]
```
but it results in a TimeoutError again.

Both user and users key-chain are still present.
```
CSR6#show run | in user
username admin privilege 15 password 0 admin
username horseinthesky privilege 15
  username horseinthesky
```

During manual configuration it is asking for confirmation when deleting a user:
```
CSR6#conf t
Enter configuration commands, one per line.  End with CNTL/Z.
CSR6(config)#no username horseinthesky
This operation will remove all username related configurations with same name.Do you want to continue? [confirm]
CSR6(config)#ip ssh pubkey-chain
CSR6(conf-ssh-pubkey)#no username horseinthesky
CSR6(conf-ssh-pubkey)#exit
```

I've tried to change regexp to this:
`"^.*\[confirm\]|^[a-z0-9.\-@\/:]{1,32}\(conf[a-z0-9.\-@\/:]{0,32}\)#$"`

It was able to delete the user but users key-chain is still there:
```
CSR6#show run | in user
username admin privilege 15 password 0 admin
  username horseinthesky
```
I'm not sure why because this is nothing new to what we have to match already.

**Comment by carlmontanari** [comment]
Hey @horseinthesky glad its (mostly) working out!

Nice creative work around for the prompt handling there! How/where did you update the regex pattern? If you updated the privilege level *after* creating the object -- as opposed to passing in your custom privilege level pattern at object creation or editing the source code to include the extra "confirm" part -- you would need to call the `conn.update_privilege_levels()` method. This method updates the "priv_map" which is basically a "map" to/from all privilege levels that scrapli uses for handling privilege escalation and de-escalation. It also updates the `comms_prompt_pattern` value of the `Channel` object.

Another very important note -- looks like you are missing a comma after the second element in your list -- this causes the second and third elements to get joined -- so scrapli basically sends "\nip ssh pub key-chain" which almost certainly will break something!

All that said, this works for me:

```
conn.privilege_levels['configuration'].pattern = r"^.*\[confirm\]|^[a-zA-Z0-9.\-@\/:]{1,32}\(conf[a-z0-9.\-@\/:]{0,32}\)#$"
conn.update_privilege_levels()
commands = [
    'no username horseinthesky',
    '\n',
    'ip ssh pubkey-chain',
    'no username horseinthesky',
    'exit'
]
output = conn.send_configs(configs=commands)
```


BUT, there is a better way! :D 

This felt like a good time to just create a wiki here to document things like this that will almost certainly come up for other people, so thats exactly what I did! Check out this link and let me know if this will work for you: https://github.com/carlmontanari/scrapli/wiki/IOSXEDriver

**Comment by horseinthesky** [comment]
OMG! So stupid of me >.<

Yes. With this comma and new pattern, everything works superbly =)
