### ISSUE TITLE
can't connect to a cisco ios switch if its name has the underscore symbol

### ISSUE THREAD

**Issue by IDQDD** [carlmontanari/scrapli#24]
**Describe the bug**

I ran into a problem with one of my switches
It's name is C2960_NFU

**To Reproduce**
1. Your script
2. What you're connecting to (vendor, platform, version)
3. Anything else relevant
```python
import logging
import time
from scrapli.driver import GenericDriver
from scrapli.driver.core import IOSXEDriver
from scrapli.driver.network_driver import PrivilegeLevel
logging.basicConfig(filename="scrapli.log", level=logging.DEBUG)
logger = logging.getLogger("scrapli")

def main():  

    mydevice = {
        "host": "sw-nfu",
        "auth_username": "backup",
        "auth_password": "backup",
        "auth_strict_key": False,        
        "ssh_config_file": True,        
    }
     
    conn = IOSXEDriver(**mydevice)
    conn.open()
    print(conn.get_prompt())
    print(conn.send_command("show ver").result)
    conn.close()

if __name__ == "__main__":
    main()
```

**Expected behavior**

Output like that:
```bash
C2960XR_NFT#
Cisco IOS Software, C2960X Software (C2960X-UNIVERSALK9-M), Version 15.2(2)E6, RELEASE SOFTWARE (fc1)
Technical Support: http://www.cisco.com/techsupport
Copyright (c) 1986-2016 by Cisco Systems, Inc.
Compiled Fri 16-Dec-16 21:27 by prod_rel_team

ROM: Bootstrap program is C2960X boot loader
BOOTLDR: C2960X Boot Loader (C2960X-HBOOT-M) Version 15.2(3r)E1, RELEASE SOFTWARE (fc1)

C2960XR_NFT uptime is 1 year, 32 weeks, 2 days, 6 hours, 26 minutes
System returned to ROM by power-on
System restarted at 08:12:17 MSK Sun Oct 21 2018
System image file is "flash:/c2960x-universalk9-mz.152-2.E6/c2960x-universalk9-mz.152-2.E6.bin"
Last reload reason: power-on
```

**Stack Trace**
```bash
Traceback (most recent call last):
  File "hfutest.py", line 54, in <module>
    main()
  File "hfutest.py", line 48, in main
    conn.open()
  File "/usr/local/lib/python3.6/dist-packages/scrapli/driver/driver.py", line 577, in open
    self.transport.open()
  File "/usr/local/lib/python3.6/dist-packages/scrapli/transport/systemssh.py", line 317, in open
    if not self._open_pty():
  File "/usr/local/lib/python3.6/dist-packages/scrapli/transport/systemssh.py", line 456, in _open_pty
    if not self._pty_isauthenticated(self.session):
  File "/usr/local/lib/python3.6/dist-packages/scrapli/decorators.py", line 77, in timeout_wrapper
    raise TimeoutError(message)
TimeoutError: Timed out determining if session is authenticated
```
**LOGS**
```bash
INFO:driver:Opening connection to sw-nfu
INFO:transport:Attempting to authenticate to sw-nfu
INFO:transport:Attempting to open session with the following command: ['ssh', 'sw-nfu', '-p', '22', '-o', 'ConnectTimeout=5', '-o', 'ServerAliveInterval=10', '-l', 'backup', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-F', '/etc/ssh/ssh_config']
DEBUG:transport:Session to host sw-nfu spawned
DEBUG:transport:Attempting to authenticate. Read: b"Warning: Permanently added 'sw-nfu,10.3.20.1' (RSA) to the list of known hosts.\r\r\n"
DEBUG:transport:Attempting to authenticate. Read: b'Password: '
INFO:transport:Found password prompt, sending password
DEBUG:transport:Attempting to determine if PTY authentication was successful
DEBUG:transport:Attempting validate authentication. Read: b'\r\n'
DEBUG:transport:Cannot determine if authenticated, 
        Read: b'\n'
DEBUG:transport:Attempting validate authentication. Read: b'\r\n'
DEBUG:transport:Cannot determine if authenticated, 
        Read: b'\n\n'
DEBUG:transport:Attempting validate authentication. Read: b'\r\nC2960XR_NFT#'
DEBUG:transport:Cannot determine if authenticated, 
        Read: b'\n\n\nC2960XR_NFT#'
DEBUG:transport:Attempting validate authentication. Read: b'\r\n'
DEBUG:transport:Cannot determine if authenticated, 
        Read: b'\n\n\nC2960XR_NFT#\n'
DEBUG:transport:Attempting validate authentication. Read: b'C2960XR_NFT#'
DEBUG:transport:Cannot determine if authenticated, 
        Read: b'\n\n\nC2960XR_NFT#\nC2960XR_NFT#'
INFO:scrapli:Timed out determining if session is authenticated
INFO:scrapli:timeout_exit is True, closing transport
DEBUG:transport:Channel to host sw-nfu closed
```

**OS (please complete the following information):**
 - OS: [e.g. Ubuntu, MacOS, etc. - Note scrapli is *not* thoroughly tested on Windows and some/many things will not
  be supported]
 - scrapli version
 - version of any optional extras (paramiko|ssh2-python|textfsm, etc.)

Ubuntu 18.04  
scrapli version 2020.5.9

**Additional context**

Custom PRIVS fixes the problem:
simple to put the underscore "_" chraracter inside the regexps that are defined in the IOSXEDriver

```python
PRIVS = {
    "exec": (PrivilegeLevel(r"^[a-z0-9.\-_@()/:]{1,32}>$", "exec", "", "", "", False, "",)),
    "privilege_exec": (
        PrivilegeLevel(
            r"^[a-z0-9.\-_@/:]{1,32}#$",
            "privilege_exec",
            "exec",
            "disable",
            "enable",
            True,
            "Password:",
        )
    ),
    "configuration": (
        PrivilegeLevel(
            r"^(\\n)?[a-z0-9.\-_@/:]{1,32}\(conf[a-z0-9.\-@/:]{0,32}\)#$",
            "configuration",
            "privilege_exec",
            "end",
            "configure terminal",
            False,
            "",
        )
    ),
}

mydevice = {
        "host": "sw-nfu",
        "auth_username": "backup",
        "auth_password": "backup",
        "auth_strict_key": False,        
        "ssh_config_file": True,             
        'privilege_levels': PRIVS,
 }
```
and all works as expected

with regards,
Nikolay Ryzhkov

**Comment by carlmontanari** [comment]
Hi Nikolay,

Thanks for another quality issue!

I was able to reproduce this, and your fix is spot on. I'm going to check the other core platforms as well to see if underscores are valid characters for hostnames on those devices as well.

I will add a few tests for each of these platforms to ensure that this is tested for in the cod base.

This should be in develop by this weekend, I'll update this issue when I get it pushed up. I'm also planning/hoping on making a release to pypi this weekend, so hopefully this will make it up there this weekend as well!

Carl

**Comment by carlmontanari** [comment]
Hello again Nikolay,

Thanks again for opening this issue -- ive got the tests added and this fix has now been merged to master and released to pypi! I'll go ahead and close this issue, but feel free to reopen if for some reason the fix does not work for you!

Thanks again,
Carl
