### ISSUE TITLE
Unable to connect to device over terminal server on scrapli 2022.7.30.post1

### ISSUE THREAD

**Issue by sngx13** [carlmontanari/scrapli#270]
**Describe the bug**
Device connection fails when using console connection over terminal server, identical configuration works on: 2022.1.30

**To Reproduce**
1. Your script:
`
#!/usr/bin/python3
from scrapli import Scrapli

username = 'automation'
password = 'automation'

device = {
    'host': '10.113.128.141',
    'port': 10012,
    'transport': 'telnet',
    'auth_strict_key': False,
    'platform': 'cisco_iosxe',
    'auth_username': username,
    'auth_password': password,
}

with Scrapli(** device, comms_return_char='\r\n') as conn:
    output = conn.send_command('show version')
    print(output.textfsm_parse_output())
`
3. What you're connecting to (vendor, platform, version): Cisco C4331
5. Anything else relevant

**Expected behavior**
Working output:

[{'version': '17.6.3a', 'rommon': '16.12(2r)', 'hostname': 'DUT-ISR4331-K9', 'uptime': '53 minutes', 'uptime_years': '', 'uptime_weeks': '', 'uptime_days': '', 'uptime_hours': '', 'uptime_minutes': '53', 'reload_reason': 'Reload Command', 'running_image': 'isr4300-universalk9.17.06.03a.SPA.bin', 'hardware': ['ISR4331/K9'], 'serial': ['FDO2516M1B1'], 'config_register': '0x2102', 'mac': [], 'restarted': ''}]

**Stack Trace**
Traceback (most recent call last):
  File "/opt/./scrapli_test.py", line 20, in <module>
    with Scrapli(** device, comms_return_char='\r\n') as conn:
  File "/usr/local/lib/python3.10/dist-packages/scrapli/driver/base/sync_driver.py", line 42, in __enter__
    self.open()
  File "/usr/local/lib/python3.10/dist-packages/scrapli/driver/base/sync_driver.py", line 100, in open
    self.channel.channel_authenticate_telnet(
  File "/usr/local/lib/python3.10/dist-packages/scrapli/decorators.py", line 216, in decorate
    return _multiprocessing_timeout(
  File "/usr/local/lib/python3.10/dist-packages/scrapli/decorators.py", line 113, in _multiprocessing_timeout
    return future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/scrapli/channel/sync_channel.py", line 361, in channel_authenticate_telnet
    buf = self.read()
  File "/usr/local/lib/python3.10/dist-packages/scrapli/channel/sync_channel.py", line 69, in read
    buf = self.transport.read()
  File "/usr/local/lib/python3.10/dist-packages/scrapli/decorators.py", line 216, in decorate
    return _multiprocessing_timeout(
  File "/usr/local/lib/python3.10/dist-packages/scrapli/decorators.py", line 113, in _multiprocessing_timeout
    return future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/dist-packages/scrapli/transport/plugins/telnet/transport.py", line 235, in read
    self._read()
  File "/usr/local/lib/python3.10/dist-packages/scrapli/transport/plugins/telnet/transport.py", line 221, in _read
    raise ScrapliConnectionError(
scrapli.exceptions.ScrapliConnectionError: encountered EOF reading from transport; typically means the device closed the connection

**OS (please complete the following information):**
 - OS: Ubuntu Server 22.04
 - scrapli version: scrapli 2022.7.30.post1

**Comment by carlmontanari** [comment]
I’ll guess that you’re going to need to mostly figure this out on your own as there will almost certainly be no way to reproduce this easily.

To start we’ll need logs, but you will probably need to check [this](https://github.com/carlmontanari/scrapli/pull/253) out as well… if there is nothing obvious in the logs/channel logs you’ll probably need to poke around in the files changed in that pr to see where things are going wrong.

**Comment by carlmontanari** [comment]
Would love to fix this if there is an issue but can't do it without participation. Feel free to reopen if we can get logs and have a conversation about how to proceed.
