### ISSUE TITLE
Problems with telnet connection

### ISSUE THREAD

**Issue by KlimchevKonstantin** [carlmontanari/scrapli#278]
Good day!

There are problems connecting via telnet to the Cisco ASA. Connecting via ssh (paramiko) works correctly.
I think the problem is in the telnet transport implementation.  

Мy knowledge of python is not enough to localize problems more precisely

```
from scrapli.driver import Driver
from pprint import pprint

import logging
logging.basicConfig(filename="scrapli.log", level=logging.DEBUG)

my_device = {
    "host": "172.16.2.6",
    "auth_username": "admin",
    "auth_password": "cisco1234",
    "auth_strict_key": False,
    "transport": "telnet",
    "port":23
#    "transport": "paramiko",
}

with Driver(**my_device) as conn:
    pprint(conn.channel.send_input("show inventory"),width=120)

```

code execution fails:

```
$ python test_asa.py
Traceback (most recent call last):
  File "/opt/saymon-agent/custom_tasks/.venv/lib/python3.10/site-packages/scrapli/transport/plugins/telnet/transport.py", line 214, in _read
    buf = self.socket.sock.recv(n)
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/saymon-agent/custom_tasks/save-config-telnet-scr/test_asa.py", line 14, in <module>
    with Driver(**my_device) as conn:
  File "/opt/saymon-agent/custom_tasks/.venv/lib/python3.10/site-packages/scrapli/driver/base/sync_driver.py", line 42, in __enter__
    self.open()
  File "/opt/saymon-agent/custom_tasks/.venv/lib/python3.10/site-packages/scrapli/driver/base/sync_driver.py", line 100, in open
    self.channel.channel_authenticate_telnet(
  File "/opt/saymon-agent/custom_tasks/.venv/lib/python3.10/site-packages/scrapli/decorators.py", line 216, in decorate
    return _multiprocessing_timeout(
  File "/opt/saymon-agent/custom_tasks/.venv/lib/python3.10/site-packages/scrapli/decorators.py", line 113, in _multiprocessing_timeout
    return future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/saymon-agent/custom_tasks/.venv/lib/python3.10/site-packages/scrapli/channel/sync_channel.py", line 359, in channel_authenticate_telnet
    buf = self.read()
  File "/opt/saymon-agent/custom_tasks/.venv/lib/python3.10/site-packages/scrapli/channel/sync_channel.py", line 69, in read
    buf = self.transport.read()
  File "/opt/saymon-agent/custom_tasks/.venv/lib/python3.10/site-packages/scrapli/decorators.py", line 216, in decorate
    return _multiprocessing_timeout(
  File "/opt/saymon-agent/custom_tasks/.venv/lib/python3.10/site-packages/scrapli/decorators.py", line 113, in _multiprocessing_timeout
    return future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/saymon-agent/custom_tasks/.venv/lib/python3.10/site-packages/scrapli/transport/plugins/telnet/transport.py", line 235, in read
    self._read()
  File "/opt/saymon-agent/custom_tasks/.venv/lib/python3.10/site-packages/scrapli/transport/plugins/telnet/transport.py", line 221, in _read
    raise ScrapliConnectionError(
scrapli.exceptions.ScrapliConnectionError: encountered EOF reading from transport; typically means the device closed the connection
```

logging:
```
DEBUG:scrapli.driver:telnet-based transport selected, ignoring ssh file arguments
DEBUG:scrapli.driver:load core transport requested
DEBUG:scrapli.driver:core transport 'telnet' loaded successfully
INFO:scrapli.driver:opening connection to '172.16.2.6' on port '23'
DEBUG:scrapli.transport:opening transport connection to '172.16.2.6' on port '23'
DEBUG:scrapli.socket:opening socket connection to '172.16.2.6' on port '23'
DEBUG:scrapli.socket:opened socket connection to '172.16.2.6' on port '23' successfully
DEBUG:scrapli.transport:transport connection to '172.16.2.6' on port '23' opened successfully
DEBUG:scrapli.channel:attempting in channel telnet authentication
DEBUG:scrapli.channel:read: b'\n\nUser Access Verification\n\nUsername: '
DEBUG:scrapli.channel:write: 'admin'
DEBUG:scrapli.channel:write: '\n'



```

if you choose another device supported in core - no problem.

scrapli==2022.01.30 (with telnetlib) - no problem

Thank you

**Comment by carlmontanari** [comment]
👋 thanks for raising this and the details/logs!

can you try the branch/pr over in #279 to see if that sorts it?

**Comment by KlimchevKonstantin** [comment]
Thank you

with #279 the problem is solved

issue #278 close
