### ISSUE TITLE
Timeout while trying to go into privilege_exec mode (Cisco IOS 15.0)

### ISSUE THREAD

**Issue by network-dave** [carlmontanari/scrapli#45]
**Describe the bug**
Timeout error while trying to acquire enable privilege. The prompt is waiting for "[pP]assword", when the device's prompt is "Enable password:"

When staying at "exec" level I am able to run commands on the device.

**To Reproduce**

Platform : Cisco C2960X - IOS 15.0
Open connection, authenticate, and acquire privilege_exec level.

Source code :
            conn = Scrapli(
                host = ip_address,
                port = int(args.port), 
                auth_username = args.username, 
                auth_password = args.password, 
                auth_secondary = args.enable_password,
                auth_strict_key = False,
                ssh_config_file = True,
                default_desired_privilege_level = "privilege_exec",
                transport = TRANSPORT,
                platform = "cisco_iosxe"
                )

**Expected behavior**
Acquire privilege_exec level

**Stack Trace**
Attempting to acquire `privilege_exec` privilege level
Attempting to escalate from exec to privilege_exec
Attempting to send input interact: enable;      expecting: ^[pP]assword:\s?$;   hidden_input: False
Read: b'enable'
timeout_exit is True, closing transport
Traceback (most recent call last):
  File "/home/id865890/.local/lib/python3.6/site-packages/scrapli/decorators.py", line 270, in multiprocessing_timeout
    result = future.get(timeout=self.timeout_duration)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 640, in get
    raise TimeoutError
multiprocessing.context.TimeoutError

**OS (please complete the following information):**
 - OS: Ubuntu 18.04 WSL
 - scrapli version: latest

**Additional context**

**Comment by carlmontanari** [comment]
Hey @network-dave -- thanks for opening this issue! I think/hope this should be an easy fix! I can test it out and get it in develop branch this weekend, but if you want to test it out, I believe all that should need to be done is to modify the privilege level regex [here](https://github.com/carlmontanari/scrapli/blob/master/scrapli/driver/core/cisco_iosxe/base_driver.py#L24). 

This regex can probably look like: `r"^(?:enable\s){0,1}password:\s$` -- looking back at this I realize that the upper/lower matching for the "p" is unnecessary since I use ignore case everywhere for the regex bits, so thats one less thing to worry about. Then to make sure we catch the "Enable" part I'd probably just optionally match "enable" since thats not showing up on all devices of course.

If you want to test that out that'd be great, otherwise this weekend I will get it tested/updated and add a test so we dont have a regression on this in the future.

Thanks again!
Carl
